In [2]:
import pandas as pd

df = pd.read_csv('data/ObesityDataSet_raw_and_data_sinthetic.csv')

df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [3]:
df['CAEC'].unique()

array(['Sometimes', 'Frequently', 'Always', 'no'], dtype=object)

In [4]:
df['female'] = df['Gender'].map({'Male': 0, 'Female': 1})
df = df.drop(['Gender'], axis=1)
df['family_history_with_overweight_adj'] = df['family_history_with_overweight'].map({'yes': 1, 'no': 0})
df = df.drop(['family_history_with_overweight'], axis=1)
df['FAVC_adj'] = df['FAVC'].map({'yes': 1, 'no': 0})
df = df.drop(['FAVC'], axis=1)
df['CAEC_adj'] = df['CAEC'].map({'Sometimes': 1, 'Frequently': 2, 'Always': 3, 'no': 0})
df = df.drop(['CAEC'], axis=1)
df['SMOKE_adj'] = df['SMOKE'].map({'yes': 1, 'no': 0})
df = df.drop(['SMOKE'], axis=1)
df['SCC_adj'] = df['SCC'].map({'yes': 1, 'no': 0})
df = df.drop(['SCC'], axis=1)
df['CALC_adj'] = df['CALC'].map({'Sometimes': 1, 'Frequently': 2, 'Always': 3, 'no': 0})
df = df.drop(['CALC'], axis=1)

df['MTRANS_adj'] = df['MTRANS'].map({'Motorbike': 1, 'Public_Transportation': 2, 'Bike': 3, 'Walking': 4, 'Automobile': 0})
df = df.drop(['MTRANS'], axis=1)


df['NObeyesdad_adj'] = df['NObeyesdad'].map({'Insufficient_Weight':0, 'Normal_Weight': 1, 'Overweight_Level_I': 2, 'Overweight_Level_II': 3, 'Obesity_Type_I': 4, 'Obesity_Type_II': 5, 'Obesity_Type_III': 6})
df = df.drop(['NObeyesdad'], axis=1)

In [5]:
df.head()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE,female,family_history_with_overweight_adj,FAVC_adj,CAEC_adj,SMOKE_adj,SCC_adj,CALC_adj,MTRANS_adj,NObeyesdad_adj
0,21.0,1.62,64.0,2.0,3.0,2.0,0.0,1.0,1,1,0,1,0,0,0,2,1
1,21.0,1.52,56.0,3.0,3.0,3.0,3.0,0.0,1,1,0,1,1,1,1,2,1
2,23.0,1.80,77.0,2.0,3.0,2.0,2.0,1.0,0,1,0,1,0,0,2,2,1
3,27.0,1.80,87.0,3.0,3.0,2.0,2.0,0.0,0,0,0,1,0,0,2,4,2
4,22.0,1.78,89.8,2.0,1.0,2.0,0.0,0.0,0,0,0,1,0,0,1,2,3

In [8]:
df.describe()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE,female,family_history_with_overweight_adj,FAVC_adj,CAEC_adj,SMOKE_adj,SCC_adj,CALC_adj,MTRANS_adj,NObeyesdad_adj
count,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.00000,2111.000000
mean,24.312600,1.701677,86.586058,2.419043,2.685628,2.008011,1.010298,0.657866,0.494079,0.817622,0.883941,1.140692,0.020843,0.045476,0.731407,1.61819,3.112269
std,6.345968,0.093305,26.191172,0.533927,0.778039,0.612953,0.850592,0.608927,0.500083,0.386247,0.320371,0.468543,0.142893,0.208395,0.515498,0.91389,1.985062
min,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
25%,19.947192,1.630000,65.473343,2.000000,2.658738,1.584812,0.124505,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,2.00000,1.000000
50%,22.777890,1.700499,83.000000,2.385502,3.000000,2.000000,1.000000,0.625350,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,2.00000,3.000000
75%,26.000000,1.768464,107.430682,3.000000,3.000000,2.477420,1.666678,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,2.00000,5.000000
max,61.000000,1.980000,173.000000,3.000000,4.000000,3.000000,3.000000,2.000000,1.000000,1.000000,1.000000,3.000000,1.000000,1.000000,3.000000,4.00000,6.000000

In [9]:
X = df.drop(['NObeyesdad_adj'], axis=1).reset_index(drop=True)
y = df['NObeyesdad_adj'].reset_index(drop=True)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=123)

In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
from sklearn.svm import SVC

clf = SVC(kernel='linear', C=10, random_state=123)
clf.fit(X_train, y_train)

SVC(C=10, kernel='linear', random_state=123)

In [13]:
from sklearn.metrics import accuracy_score

y_train_true = y_train
y_train_pred = clf.predict(X_train)
y_test_true = y_test
y_test_pred = clf.predict(X_test)


print(f"Acurácia de Treino: {round(accuracy_score(y_train_true, y_train_pred), 2)}")
print('\n ---------------------------\n')
print(f"Acurácia de Teste: {round(accuracy_score(y_test_true, y_test_pred), 2)}")

Acurácia de Treino: 0.98

 ---------------------------

Acurácia de Teste: 0.97